baseURL = "https://lanziani.com/"
languageCode = "en-us"
title = "Luca Lanziani"
theme = "noteworthy"
paginate = 10

[params]
math = true
description = "Stories from an Italian Software Engineer"
profilePicture = "images/profile.png"
showReadMore = true
frontpagePost = "I was highly skeptical, but now I'm a believer."  # Set to a post title to feature it on the homepage, or leave empty for most recent
linkedin = "https://www.linkedin.com/in/lucalanziani/"
email = "mailto:luca+site@lanziani.com"
twitter = "https://twitter.com/lucalanziani"
github = "https://github.com/LucaLanziani"
#mastodon = "https://mastodon.uno/@lucalanziani"
#youtube = "https://www.youtube.com/c/lucalanziani"
# twitch = "https://www.twitch.tv/lucalanziani"


[taxonomies]
tag = "tags"
series = "series"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

# Menu links along the sidebar navigation.
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/posts/"
weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
